#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

REQUIREMENTS="requirements.txt"
VENV="venv"

set -x

if [ -z "$GITHUB_ACTIONS" ]; then
    "$PYTHON" -m venv "$VENV"
    PIP="$VENV/bin/pip"
else
    PIP="pip"
fi

"$PIP" uninstall -y $(pip show setuptools | awk '/^Requires: / {print $2}' | tr ',' '\n') setuptools
"$PIP" install --ignore-installed pip==21.3.1
"$PIP" install --ignore-installed --index-url 'https://:2021-11-18T00:19:51.290101Z@time-machines-pypi.sealsecurity.io/' setuptools
"$PIP" install --ignore-installed --index-url 'https://:2021-11-18T00:19:51.290101Z@time-machines-pypi.sealsecurity.io/' -r "$REQUIREMENTS"
"$PIP" install -e .
